services:
  url-shortener-app:
    image: ${DOCKERHUB_USERNAME}/url-shortener:latest
    container_name: url-shortener
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./out:/app/out