name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]


jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: Linter
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.6.0
        args: --timeout=5m

    - name: Run tests with coverage
      run: go test -v -race -coverprofile=coverage.txt ./...

    - name: Verify build
      run: go build -v -o /dev/null ./cmd/url-shortener